export const ROUTE_PATHS = {
  landing: '/',
  auth: '/auth',
  joinWithCode: '/join/:code',
  manualCodeEntry: '/code',
  home: '/home',
  adminHome: '/admin',
  superHome: '/super',
  offers: '/offers',
  directory: '/directory',
  profile: '/profile',
  privacySettings: '/settings/privacy',
  adminStage1: '/admin/recruitment/:orgId/:cycleId/stage-1',
  adminStage2: '/admin/recruitment/:orgId/:cycleId/stage-2',
  adminMessages: '/admin/recruitment/:orgId/:cycleId/messages',
  adminMembers: '/admin/members/:orgId',
  superUniversities: '/super/universities',
  superOrganizations: '/super/organizations',
  superAdmins: '/super/admins',
  superCycles: '/super/cycles',
} as const
